fragment PartnersAttributes on WebPartners {
    docs {
        id
        name
        link {
            href
            text
            target
        }
        image {
            ...MediaAttributes
        }
    }
}
