fragment SocialsAttributes on WebSocials {
    docs {
        id
        link {
            href
            text
            target
        }
        icon
        backgroundImage {
            ...MediaAttributes
        }
    }
}
