fragment WebSocialsAttributes on WebSocials {
    docs {
        id
        link {
            href
            text
            target
        }
        icon
        backgroundImage {
            ...WebImageAttributes
        }
    }
}
