query findPlants($pagination: Boolean, $limit: Int) {
  Plants(pagination: $pagination, limit: $limit) {
    docs {
      germanName
      scientificName
      family {
        germanName
        scientificName
      }
      toxicityLevel {
        title
      }
    }
  }
}