query findDashboardTickets($where: DashboardTicket_where) {
    DashboardTickets(where: $where) {
        docs {
            id
            title
            status
            priority
            updatedAt
            createdAt
            category {
                id
                title
            }
        }
    }
}
