query getUserData {
    meUser {
        user {
            enrolledCourses {
                docs {
                    name
                    videoLessons {
                        slug
                        title
                    }
                }
            }
            roles {
                slug
                name
            }
        }
    }
}
