fragment AccordionsAttributes on PublicAccordions {
    id
    blockName
    blockType
    publicAccordionsContent: content {
        title
        items {
            id
            title
            content
        }
    }
    publicAccordionsSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
