fragment AnimatedTextAttributes on PublicAnimatedText {
    id
    blockName
    blockType
    publicAnimatedTextContent: content {
        text
    }
    publicAnimatedTextSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
