fragment CourseListAttributes on PublicCourseList {
    id
    blockName
    blockType
    publicCourseListContent: content {
        title
        courses {
            id
            name
            description
            place
            modules {
                docs {
                    date
                }
            }
        }
    }
    publicCourseListSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
