fragment HeroLargeAttributes on PublicHeroLarge {
    id
    blockName
    blockType
    publicHeroLargeContent: content {
        title
        image {
            ...PublicImageAttributes
        }
    }
    publicHeroLargeSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
