fragment HeroSmallAttributes on PublicHeroSmall {
    id
    blockName
    blockType
    publicHeroSmallContent: content {
        title
        image {
            ...PublicImageAttributes
        }
        link {
            text
            href
            target
        }
    }
    publicHeroSmallSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
