fragment HighlightedLinksAttributes on PublicHighlightedLinks {
    id
    blockName
    blockType
    publicHighlightedLinksContent: content {
        links {
            id
            text
            url
            target
            image {
                ...PublicImageAttributes
            }
        }
    }
    publicHighlightedLinksSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
