fragment ImageTextAttributes on PublicImageText {
    id
    blockName
    blockType
    publicImageTextContent: content {
        title
        textTop
        textHighlight
        textBottom
        link {
            text
            href
            target
        }
        image {
            ...PublicImageAttributes
        }
    }
    publicImageTextSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
