fragment MoodPictureAttributes on PublicMoodPicture {
    id
    blockName
    blockType
    publicMoodPictureContent: content {
        image {
            ...PublicImageAttributes
        }
    }
    publicMoodPictureSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
