fragment TitleElementAttributes on PublicTitleElement {
    id
    blockName
    blockType
    publicTitleElementContent: content {
        title
    }
    publicTitleElementSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
