fragment DashboardImageElementAttributes on DashboardImageElement {
    id
    blockName
    blockType

    dashboardImageElementContent: content {
        image {
            ...DashboardImageAttributes
        }
    }
}
