fragment DashboardImageTextAttributes on DashboardImageText {
    id
    blockName
    blockType

    dashboardImageTextContent: content {
        image {
            ...DashboardImageAttributes
        }
        text
    }
}
