fragment AccordionsAttributes on WebAccordions {
    id
    blockName
    blockType
    webAccordionsContent: content {
        title
        items {
            id
            title
            content
        }
    }
    webAccordionsSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
