fragment AnimatedTextAttributes on WebAnimatedText {
    id
    blockName
    blockType
    webAnimatedTextContent: content {
        text
    }
    webAnimatedTextSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
