fragment BookListAttributes on WebBookList {
    id
    blockName
    blockType
    webBookListContent: content {
        title
        books {
            id
            title
            infos
            description
            cover {
                ...WebImageAttributes
            }
            link {
                text
                href
                target
            }
        }
    }
    webBookListSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
