fragment BookListAttributes on PublicBookList {
    id
    blockName
    blockType
    publicBookListContent: content {
        title
        books {
            id
            title
            infos
            description
            cover {
                ...PublicImageAttributes
            }
            link {
                text
                href
                target
            }
        }
    }
    publicBookListSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
