fragment CourseListAttributes on WebCourseList {
    id
    blockName
    blockType
    webCourseListContent: content {
        title
        courses {
            id
            name
            description
            place
        }
    }
    webCourseListSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
