fragment HeroSmallAttributes on WebHeroSmall {
    id
    blockName
    blockType
    webHeroSmallContent: content {
        title
        image {
            ...WebImageAttributes
        }
        link {
            text
            href
            target
        }
    }
    webHeroSmallSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
