fragment HeroSmallAttributes on WebHeroSmall {
    id
    blockName
    blockType
    webHeroSmallContent: content {
        title
        image {
            ...MediaAttributes
        }
        link {
            label
            url
            target
        }
    }
    webHeroSmallSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
