fragment HeroLargeAttributes on WebHeroLarge {
    id
    blockName
    blockType
    webHeroLargeContent: content {
        title
        image {
            ...MediaAttributes
        }
    }
    webHeroLargeSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
