fragment ImageTextAttributes on WebImageText {
    id
    blockName
    blockType
    webImageTextContent: content {
        title
        textTop
        textHighlight
        textBottom
        link {
            text
            href
            target
        }
        image {
            ...MediaAttributes
        }
    }
    webImageTextSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
