fragment InfosAttributes on WebInfos {
    id
    blockName
    blockType
    webInfosContent: content {
        infos {
            id
            infos {
                title
                text
            }
            link {
                text
                href
                target
            }
        }
    }
    webInfosSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
