fragment InfosAttributes on PublicInfos {
    id
    blockName
    blockType
    publicInfosContent: content {
        infos {
            id
            title
            text
        }
        link {
            text
            href
            target
        }
    }
    publicInfosSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
