fragment MoodPictureAttributes on WebMoodPicture {
    id
    blockName
    blockType
    webMoodPictureContent: content {
        image {
            ...WebImageAttributes
        }
    }
    webMoodPictureSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
