fragment SwiperLargeAttributes on WebSwiperLarge {
    id
    blockName
    blockType
    webSwiperLargeContent: content {
        title
        items {
            id
            title
            infos
            description
            link {
                label
                url
                target
            }
            image {
                ...MediaAttributes
            }
        }
    }
    webSwiperLargeSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
