fragment SwiperSimpleAttributes on WebSwiperSimple {
    id
    blockName
    blockType
    webSwiperSimpleContent: content {
        slides {
            id
            title
            images {
                id
                image {
                    ...WebImageAttributes
                }
            }
        }
    }
    webSwiperSimpleSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
