fragment SwiperLargeAttributes on PublicSwiperLarge {
    id
    blockName
    blockType
    publicSwiperLargeContent: content {
        title
        items {
            id
            title
            infos
            description
            link {
                text
                href
                target
            }
            image {
                ...PublicImageAttributes
            }
        }
    }
    publicSwiperLargeSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
