fragment SwiperCardAttributes on PublicSwiperCard {
    id
    blockName
    blockType
    publicSwiperCardContent: content {
        cards {
            id
            image {
                ...PublicImageAttributes
            }
            info
            date
            title
            link {
                text
                href
                target
            }
        }
    }
    publicSwiperCardSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
