fragment SwiperSimpleAttributes on PublicSwiperSimple {
    id
    blockName
    blockType
    publicSwiperSimpleContent: content {
        slides {
            id
            title
            images {
                id
                image {
                    ...PublicImageAttributes
                }
            }
        }
    }
    publicSwiperSimpleSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
