fragment TextElementAttributes on WebTextElement {
    id
    blockName
    blockType
    webTextElementContent: content {
        title
        content
        link {
            text
            href
            target
        }
    }
    webTextElementSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
