fragment TextElementAttributes on PublicTextElement {
    id
    blockName
    blockType
    publicTextElementContent: content {
        title
        content
        link {
            text
            href
            target
        }
    }
    publicTextElementSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
