fragment TitleElementAttributes on WebTitleElement {
    id
    blockName
    blockType
    webTitleElementContent: content {
        title
    }
    webTitleElementSettings: settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        style
    }
}
