fragment AccordionsAttributes on WebAccordions {
    data {
        title
        AccordionItems {
            id
            title
            content
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        accordionsStyle: style
    }
}
