fragment HeaderAttributes on ComponentSharedHeader {
    links {
        ...LinkAttributes
    }
    sidebar {
        ...SidebarAttributes
    }
    ctaButtons {
        ...HeaderCtaButtonsAttributes
    }
}
