query findPublicPages($where: PublicPage_where) {
    PublicPages: PublicPages(where: $where) {
        docs {
            id
            slug
            updatedAt
            createdAt
            title
            description
            image {
                ...PublicImageAttributes
            }
            keywords
            noIndex
            canonical
            schemaType
            blocks {
                __typename
                ... on PublicAccordions {
                    ...AccordionsAttributes
                }
                ... on PublicAnimatedText {
                    ...AnimatedTextAttributes
                }
                ... on PublicBookList {
                    ...BookListAttributes
                }
                ... on PublicCourseList {
                    ...CourseListAttributes
                }
                ... on PublicHeroLarge {
                    ...HeroLargeAttributes
                }
                ... on PublicHeroSmall {
                    ...HeroSmallAttributes
                }
                ... on PublicHighlightedLinks {
                    ...HighlightedLinksAttributes
                }
                ... on PublicImageText {
                    ...ImageTextAttributes
                }
                ... on PublicInfos {
                    ...InfosAttributes
                }
                ... on PublicMoodPicture {
                    ...MoodPictureAttributes
                }
                ... on PublicSwiperCard {
                    ...SwiperCardAttributes
                }
                ... on PublicSwiperLarge {
                    ...SwiperLargeAttributes
                }
                ... on PublicSwiperSimple {
                    ...SwiperSimpleAttributes
                }
                ... on PublicTextElement {
                    ...TextElementAttributes
                }
                ... on PublicTitleElement {
                    ...TitleElementAttributes
                }
            }
        }
        hasNextPage
        hasPrevPage
        limit
        nextPage
        offset
        page
        pagingCounter
        prevPage
        totalDocs
        totalPages
    }
}
