query findGlobals {
    PublicHeader {
        ...PublicHeaderAttributes
    }
    PublicFooter {
        ...PublicFooterAttributes
    }
    PublicSidebar {
        ...PublicSidebarAttributes
    }
    Contact {
        ...ContactAttributes
    }
    PublicPartners {
        docs {
            ...PublicPartnerAttributes
        }
    }
    PublicSocials {
        docs {
            ...PublicSocialAttributes
        }
    }
    PublicTextBlocks {
        docs {
            ...PublicTextBlockAttributes
        }
    }
}
