query findPages($filters: PageFiltersInput) {
    pages: pages(filters: $filters) {
        seo {
            ...SeoAttributes
        }
        components {
            __typename
            ... on ComponentContentAccordions {
                ...AccordionsAttributes
            }
            ... on ComponentContentAnimatedText {
                ...AnimatedTextAttributes
            }
            ... on ComponentContentBookList {
                ...BookListAttributes
            }
            ... on ComponentContentCourseList {
                ...CourseListAttributes
            }
            ... on ComponentContentHeroLarge {
                ...HeroLargeAttributes
            }
            ... on ComponentContentHeroSmall {
                ...HeroSmallAttributes
            }
            ... on ComponentContentImageText {
                ...ImageTextAttributes
            }
            ... on ComponentContentInfos {
                ...InfosAttributes
            }
            ... on ComponentContentMoodPicture {
                ...MoodPictureAttributes
            }
            ... on ComponentContentTextElement {
                ...TextElementAttributes
            }

            ... on Error {
                ...ErrorAttributes
            }
        }
    }
}
