query findGlobals {
    WebHeader {
        ...WebHeaderAttributes
    }
    WebFooter {
        ...WebFooterAttributes
    }
    WebSidebar {
        ...WebSidebarAttributes
    }
    Contact {
        ...ContactAttributes
    }
    WebPartners {
        docs {
            ...WebPartnerAttributes
        }
    }
    WebSocials {
        docs {
            ...WebSocialAttributes
        }
    }
    WebTextBlocks {
        docs {
            ...WebTextBlockAttributes
        }
    }
}
