fragment AccordionsAttributes on ComponentContentAccordions {
    data {
        title
        accordions {
            ...AccordionAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        accordionsStyle: style
    }
}
