fragment AnimatedTextAttributes on ComponentContentAnimatedText {
    data {
        id
        text
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        animatedTextStyle: style
    }
}
