fragment BookListAttributes on ComponentContentBookList {
    data {
        title
        books {
            ...BookAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        bookListStyle: style
    }
}
