fragment CourseListAttributes on ComponentContentCourseList {
    data {
        title
        courses {
            ...CourseAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        courseListStyle: style
    }
}
