fragment HeroSmallAttributes on ComponentContentHeroSmall {
    data {
        id
        title
        link {
            id
            href
            text
        }
        image {
            ...UploadFileAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
