fragment HighlightedLinksAttributes on ComponentContentHighlightedLinks {
    data {
        imageLinks {
            ...ImageLinkAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        highlightedLinsStyle: style
    }
}
