fragment ImageTextAttributes on ComponentContentImageText {
    data {
        title
        image {
            ...UploadFileAttributes
        }
        textTop
        textHighlight
        textBottom
        link {
            ...LinkAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        imageTextStyle: style
    }
}
