fragment ImageTextAttributes on ComponentContentImageText {
    data {
        title
        image {
            ...UploadFileAttributes
        }
        textTop
        textHighlight
        textBottom
        link {
            ...LinkAttributes
        }
    }
    settings {
        default
    }
}
