fragment InfosAttributes on ComponentContentInfos {
    data {
        infos {
            ...InfoAttributes
        }
        link {
            ...LinkAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        infosStyle: style
    }
}
