fragment MoodPictureAttributes on ComponentContentMoodPicture {
    data {
        image {
            ...UploadFileAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
