fragment SwiperLargeAttributes on ComponentContentSwiperLarge {
    data {
        title
        items {
            ...SwiperLargeItemAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
