fragment SwiperCardAttributes on ComponentContentSwiperCard {
    data {
        title
        cards {
            ...SwiperCardItemAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
    }
}
