fragment SwiperLargeAttributes on ComponentContentSwiperLarge {
    data {
        title
        items {
            ...SwiperLargeItemAttributes
        }
    }
    settings {
        default
    }
}
