fragment SwiperSimpleAttributes on ComponentContentSwiperSimple {
    data {
        title
        images {
            ...UploadFileAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        swiperSimpleStyle: style
    }
}
