fragment TextElementAttributes on ComponentContentTextElement {
    data {
        title
        content
        link {
            ...LinkAttributes
        }
    }
    settings {
        spacing {
            marginTop
            marginBottom
            paddingTop
            paddingBottom
        }
        textElementStyle: style
    }
}
