fragment TextElementAttributes on ComponentContentTextElement {
    data {
        title
        content
        link {
            ...LinkAttributes
        }
    }
    settings {
        default
    }
}
