fragment CourseAttributes on ComponentElementsCourse {
    title
    description
    link {
        ...LinkAttributes
    }
    dates(pagination: { limit: -1 }) {
        ...SimpleDateAttributes
    }
}
