fragment SwiperLargeItemAttributes on ComponentElementsSwiperLargeItem {
    image {
        ...UploadFileAttributes
    }
    infos
    title
    description
    links {
        ...LinkAttributes
    }
}
